name: aldesk_monorepo

packages:
  - app/
  - packages/**

scripts:
  fmt:
    exec: dart format .

  prepare: melos bootstrap

  dev:
    exec: flutter run
    packageFilters:
      flutter: true
  
  icon:
    exec: dart run flutter_launcher_icons
    packageFilters:
      flutter: true
      dependsOn: "flutter_launcher_icons"
  
  export:
    exec: dart run scripts.dart exports
    packageFilters:
      scope: "anilist"

  gen:
    exec: dart run build_runner build -d
    packageFilters:
      dependsOn: "build_runner"

  test:al:
    exec: dart test
    packageFilters:
      scope: "anilist"