name: aldesk
description: "Anilist client for dekstop"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  dart_jsonwebtoken: ^2.14.2
  flutter:
    sdk: flutter
  anilist:
    path: ../packages/anilist
  flutter_riverpod: ^2.6.1
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  logger: ^2.5.0
  package_info_plus: ^8.1.2
  path_provider: ^2.1.5
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.4
  toastification: ^2.3.0
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.2
  async_builder: ^1.3.1+1
  window_size: ^0.1.0
  flutter_markdown: ^0.7.4+3
  flutter_form_builder: ^9.7.0
  form_builder_validators: ^11.1.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  image_path: "assets/logo.png"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48