# build.yaml

targets:
  $default:
    builders:
      graphql_codegen:
        options:
          outputDirectory: ../models
          namingSeparator: ""
          scalars:
            Json:
              type: Map<String, dynamic>
            CountryCode:
              type: String