name: anilist
description: "Anilist client for Dart"
version: 1.0.0

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  gql: ^1.0.0+1
  http: ^1.2.2

dev_dependencies:
  build_runner: ^2.4.13
  dotenv: ^4.2.0
  graphql_codegen: ^1.1.0
  lints: ^5.0.0
  test: ^1.25.8
