targets:
  $default:
    builders:
      json_serializable:
        enabled: true
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: anilist|lib/src/graphql/schema.graphql
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: anilist|lib/src/graphql/schema.graphql
